spring:
  profiles:
    active: dev
  application:
    name: localstack-aws-integration

  cloud:
    aws:
      sns:
        endpoint: ${SNS_ENDPOINT:http://localhost:4566/arn:aws:sqs:us-east-1:000000000000:my-queue}
        region: ${REGION_KEY:us-east-1}
        enabled: true
      credentials:
        secret-key: ${SECRET_KEY:test-secret}
        access-key: ${ACCESS_KEY:test-key}


info:
  topic: ${TOPIC_NAME:arn:aws:sns:us-east-1:000000000000:my-topic}

server:
  port: ${PORT:8090}
